# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/githubDARIAEngineering/dcaf_case_management//administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    groups:
      ruby-minor-patch:
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10

- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    js-minor-patch:
      update-types:
        - "minor"
        - "patch"
  labels:
    - "dependencies"


