version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 5
  reviewers:
    - "xmunoz"
    - "colinxfleming"
    - "lomky"
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 5
  reviewers:
    - "xmunoz"
    - "colinxfleming"
    - "lomky"
