inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Lint/AmbiguousRegexpLiteral:
  Enabled: false # this is a tremendously stupid rule

AllCops:
  TargetRubyVersion: 3.4.4
  Exclude:
    # Only really want app and test   
    - bin/**/*
    - config/**/*
    - db/**/*
    - lib/**/*
    - log/**/*
    - public/**/*
    - scripts/**/*
    - tmp/**/*
    - vendor/**/*
