Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false # this is a tremendously stupid rule

Rails:
  Enabled: true

AllCops:
  Exclude: 
    - db/**/*
    - bin/**/*
    - script/**/*
    - lib/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*
    - config/**/*
    - bin/**/*
