Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false # this is a tremendously stupid rule

Rails:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.5.3
  Exclude: 
    - db/**/*
    - bin/**/*
    - script/**/*
    - lib/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*
    - config/**/*
    - bin/**/*
