nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.1.cjs

supportedArchitectures:
  os:
    - "current"
    - "darwin"
    - "linux"
    - "win32"

  cpu:
    - "current"
    - "x86"
    - "x64"
    - "arm64"
    - "ia32"
